# -*- coding: utf-8 -*-
"""카페_전처리.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aH4SB1OgaTfVzMSayWNnMLxd2sQSGDLZ
"""

import pandas as pd

cafe_data = pd.read_csv('/content/drive/MyDrive/미니 프로젝트/data/카페_train.csv')

df = cafe_data.dropna(axis=1)
df.head()

# 직원이 질문하는 경우 & 소비자가 대답하는 경우 삭제

x1 = df[(df['발화자']=='s')&(df['QA여부']=='q')].index
x2 = df[(df['발화자']=='c')&(df['QA여부']=='a')].index

df = df.drop(x1)
df = df.drop(x2)
df.reset_index(inplace = True, drop = True)

# QA 정렬대로 뽑아오기
Q = []
A = []
Intent = []

for i in df.index:
  if df['QA여부'][i] == 'q' and df['QA여부'][i+1] == 'a':
    Q.append(df.loc[i]['발화문'])
    A.append(df.loc[i+1]['발화문'])
    Intent.append(df.loc[i]['인텐트'])

data= pd.DataFrame({'Q':Q,
                'A':A,
                'Intent' :Intent})


data

# 중복 질문 제거
# 데이터: 72559 --> 중복 제거 후 데이터: 66041 
data.drop_duplicates(['Q'], inplace = True)
data.reset_index(inplace = True, drop = True)

# -------------------------------------------
# Intent 삭제
# 데이터: 66041 --> Intent 삭제 후 데이터: 50201
# -------------------------------------------

# 매장, 멤버십, 예약, 행사, 웹사이트, AS
del_intent = data[data['Intent'].str.contains('매장|멤버십|예약|행사|웹사이트|AS')].index
data = data.drop(del_intent)

# 제품_불량
product_poor = data[data['Intent'].str.contains('제품_불량')].index
data = data.drop(product_poor)

# 제품_추천
product_recommend = data[data['Intent'].str.contains('제품_추천')].index
data = data.drop(product_recommend)

# 제품_용도
product_usage = data[data['Intent'].str.contains('제품_용도')].index
data = data.drop(product_usage)

data.reset_index(inplace = True, drop = True)

# 날짜 묻는 질문/날짜로 대답하는 답변 제거
# 데이터: 50201 --> 제거 후 데이터: 50034/49582
product_date_q = data[data['Q'].str.contains('1월|2월|3월|4월|5월|6월|7월|8월|9월|10월')].index
data = data.drop(product_date_q)

product_date_a = data[data['A'].str.contains('1월|2월|3월|4월|5월|6월|7월|8월|9월|10월')].index
data = data.drop(product_date_a)

data.reset_index(inplace=True, drop=True)

# 필요 없는 정보 제거
# 데이터: 49582 --> 제거 후 데이터: 49352
extra = data[data['Q'].str.contains('설빙|베스킨라빈스|나무|단청|도마|그림')].index
data = data.drop(extra)

data.reset_index(inplace=True, drop=True)

lst = list(data['Intent'])
lst2 = [i.split('_')[0] if i.split('_')[0] != '제품' else i.split('_')[0] +'_'+ i.split('_')[2] for i in lst]

data['Intent'] = lst2

data['Intent'].value_counts()

DATA_PATH = '/content/drive/MyDrive/미니 프로젝트/data/'
data.to_csv(DATA_PATH + 'cafe_qa_train.csv', index=False)

# data_frame = data

# #################################
# ### 2. Intent 항목 레이블, 원핫인코딩(의도분석에 이용)
# #################################

# from sklearn.preprocessing import LabelEncoder
# from sklearn.preprocessing import OneHotEncoder

# #레이블 인코딩
# lab_encoder = LabelEncoder()
# lab_encoder.fit(data_frame['Intent'].unique())
# lst = lab_encoder.classes_
# label_list = dict(zip(lst, range(len(lst))))

# print(label_list)    #원래값-숫자 목록

# #레이블 데이터 적용
# lab_in=lab_encoder.transform(data_frame['Intent'])   # label 값
# ori_in=lab_encoder.inverse_transform(lab_in)         # 원래 값
# data_frame['Intent'] = lab_in